/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl4.myDsl.AddTo;
import org.xtext.example.mydsl4.myDsl.Collision;
import org.xtext.example.mydsl4.myDsl.Inertial;
import org.xtext.example.mydsl4.myDsl.Joint;
import org.xtext.example.mydsl4.myDsl.Link;
import org.xtext.example.mydsl4.myDsl.MyDslPackage;
import org.xtext.example.mydsl4.myDsl.Origin;
import org.xtext.example.mydsl4.myDsl.ReUseAble;
import org.xtext.example.mydsl4.myDsl.Visual;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add To</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getJoint <em>Joint</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getCollision <em>Collision</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getVisual <em>Visual</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getInertial <em>Inertial</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AddToImpl#getOrigin <em>Origin</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AddToImpl extends MinimalEObjectImpl.Container implements AddTo {
	/**
	 * The cached value of the '{@link #getLink() <em>Link</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getLink()
	 * @generated
	 * @ordered
	 */
	protected Link link;

	/**
	 * The cached value of the '{@link #getJoint() <em>Joint</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getJoint()
	 * @generated
	 * @ordered
	 */
	protected Joint joint;

	/**
	 * The cached value of the '{@link #getCollision() <em>Collision</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getCollision()
	 * @generated
	 * @ordered
	 */
	protected EList<Collision> collision;

	/**
	 * The cached value of the '{@link #getVisual() <em>Visual</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getVisual()
	 * @generated
	 * @ordered
	 */
	protected EList<Visual> visual;

	/**
	 * The cached value of the '{@link #getInertial() <em>Inertial</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getInertial()
	 * @generated
	 * @ordered
	 */
	protected EList<Inertial> inertial;

	/**
	 * The cached value of the '{@link #getOrigin() <em>Origin</em>}' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getOrigin()
	 * @generated
	 * @ordered
	 */
	protected EList<Origin> origin;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AddToImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MyDslPackage.Literals.ADD_TO;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Link getLink() {
		if (link != null && link.eIsProxy()) {
			InternalEObject oldLink = (InternalEObject)link;
			link = (Link)eResolveProxy(oldLink);
			if (link != oldLink) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.ADD_TO__LINK, oldLink, link));
			}
		}
		return link;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Link basicGetLink() {
		return link;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setLink(Link newLink) {
		Link oldLink = link;
		link = newLink;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ADD_TO__LINK, oldLink, link));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Joint getJoint() {
		if (joint != null && joint.eIsProxy()) {
			InternalEObject oldJoint = (InternalEObject)joint;
			joint = (Joint)eResolveProxy(oldJoint);
			if (joint != oldJoint) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.ADD_TO__JOINT, oldJoint, joint));
			}
		}
		return joint;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Joint basicGetJoint() {
		return joint;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setJoint(Joint newJoint) {
		Joint oldJoint = joint;
		joint = newJoint;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ADD_TO__JOINT, oldJoint, joint));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Collision> getCollision() {
		if (collision == null) {
			collision = new EObjectContainmentEList<Collision>(Collision.class, this, MyDslPackage.ADD_TO__COLLISION);
		}
		return collision;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Visual> getVisual() {
		if (visual == null) {
			visual = new EObjectContainmentEList<Visual>(Visual.class, this, MyDslPackage.ADD_TO__VISUAL);
		}
		return visual;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Inertial> getInertial() {
		if (inertial == null) {
			inertial = new EObjectContainmentEList<Inertial>(Inertial.class, this, MyDslPackage.ADD_TO__INERTIAL);
		}
		return inertial;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Origin> getOrigin() {
		if (origin == null) {
			origin = new EObjectContainmentEList<Origin>(Origin.class, this, MyDslPackage.ADD_TO__ORIGIN);
		}
		return origin;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case MyDslPackage.ADD_TO__COLLISION:
				return ((InternalEList<?>)getCollision()).basicRemove(otherEnd, msgs);
			case MyDslPackage.ADD_TO__VISUAL:
				return ((InternalEList<?>)getVisual()).basicRemove(otherEnd, msgs);
			case MyDslPackage.ADD_TO__INERTIAL:
				return ((InternalEList<?>)getInertial()).basicRemove(otherEnd, msgs);
			case MyDslPackage.ADD_TO__ORIGIN:
				return ((InternalEList<?>)getOrigin()).basicRemove(otherEnd, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case MyDslPackage.ADD_TO__LINK:
				if (resolve) return getLink();
				return basicGetLink();
			case MyDslPackage.ADD_TO__JOINT:
				if (resolve) return getJoint();
				return basicGetJoint();
			case MyDslPackage.ADD_TO__COLLISION:
				return getCollision();
			case MyDslPackage.ADD_TO__VISUAL:
				return getVisual();
			case MyDslPackage.ADD_TO__INERTIAL:
				return getInertial();
			case MyDslPackage.ADD_TO__ORIGIN:
				return getOrigin();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case MyDslPackage.ADD_TO__LINK:
				setLink((Link)newValue);
				return;
			case MyDslPackage.ADD_TO__JOINT:
				setJoint((Joint)newValue);
				return;
			case MyDslPackage.ADD_TO__COLLISION:
				getCollision().clear();
				getCollision().addAll((Collection<? extends Collision>)newValue);
				return;
			case MyDslPackage.ADD_TO__VISUAL:
				getVisual().clear();
				getVisual().addAll((Collection<? extends Visual>)newValue);
				return;
			case MyDslPackage.ADD_TO__INERTIAL:
				getInertial().clear();
				getInertial().addAll((Collection<? extends Inertial>)newValue);
				return;
			case MyDslPackage.ADD_TO__ORIGIN:
				getOrigin().clear();
				getOrigin().addAll((Collection<? extends Origin>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case MyDslPackage.ADD_TO__LINK:
				setLink((Link)null);
				return;
			case MyDslPackage.ADD_TO__JOINT:
				setJoint((Joint)null);
				return;
			case MyDslPackage.ADD_TO__COLLISION:
				getCollision().clear();
				return;
			case MyDslPackage.ADD_TO__VISUAL:
				getVisual().clear();
				return;
			case MyDslPackage.ADD_TO__INERTIAL:
				getInertial().clear();
				return;
			case MyDslPackage.ADD_TO__ORIGIN:
				getOrigin().clear();
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case MyDslPackage.ADD_TO__LINK:
				return link != null;
			case MyDslPackage.ADD_TO__JOINT:
				return joint != null;
			case MyDslPackage.ADD_TO__COLLISION:
				return collision != null && !collision.isEmpty();
			case MyDslPackage.ADD_TO__VISUAL:
				return visual != null && !visual.isEmpty();
			case MyDslPackage.ADD_TO__INERTIAL:
				return inertial != null && !inertial.isEmpty();
			case MyDslPackage.ADD_TO__ORIGIN:
				return origin != null && !origin.isEmpty();
		}
		return super.eIsSet(featureID);
	}

} //AddToImpl
