/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl4.myDsl.AssignNewValue;
import org.xtext.example.mydsl4.myDsl.MyDslPackage;
import org.xtext.example.mydsl4.myDsl.Ref;
import org.xtext.example.mydsl4.myDsl.URDFAttrNumeric;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Assign New Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AssignNewValueImpl#getGetRef <em>Get Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.impl.AssignNewValueImpl#getNewValue <em>New Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AssignNewValueImpl extends MinimalEObjectImpl.Container implements AssignNewValue {
	/**
	 * The cached value of the '{@link #getGetRef() <em>Get Ref</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getGetRef()
	 * @generated
	 * @ordered
	 */
	protected Ref getRef;

	/**
	 * The cached value of the '{@link #getNewValue() <em>New Value</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getNewValue()
	 * @generated
	 * @ordered
	 */
	protected URDFAttrNumeric newValue;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssignNewValueImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MyDslPackage.Literals.ASSIGN_NEW_VALUE;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Ref getGetRef() {
		return getRef;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetGetRef(Ref newGetRef, NotificationChain msgs) {
		Ref oldGetRef = getRef;
		getRef = newGetRef;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ASSIGN_NEW_VALUE__GET_REF, oldGetRef, newGetRef);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setGetRef(Ref newGetRef) {
		if (newGetRef != getRef) {
			NotificationChain msgs = null;
			if (getRef != null)
				msgs = ((InternalEObject)getRef).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ASSIGN_NEW_VALUE__GET_REF, null, msgs);
			if (newGetRef != null)
				msgs = ((InternalEObject)newGetRef).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ASSIGN_NEW_VALUE__GET_REF, null, msgs);
			msgs = basicSetGetRef(newGetRef, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ASSIGN_NEW_VALUE__GET_REF, newGetRef, newGetRef));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public URDFAttrNumeric getNewValue() {
		return newValue;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetNewValue(URDFAttrNumeric newNewValue, NotificationChain msgs) {
		URDFAttrNumeric oldNewValue = newValue;
		newValue = newNewValue;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE, oldNewValue, newNewValue);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setNewValue(URDFAttrNumeric newNewValue) {
		if (newNewValue != newValue) {
			NotificationChain msgs = null;
			if (newValue != null)
				msgs = ((InternalEObject)newValue).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE, null, msgs);
			if (newNewValue != null)
				msgs = ((InternalEObject)newNewValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE, null, msgs);
			msgs = basicSetNewValue(newNewValue, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE, newNewValue, newNewValue));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case MyDslPackage.ASSIGN_NEW_VALUE__GET_REF:
				return basicSetGetRef(null, msgs);
			case MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE:
				return basicSetNewValue(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case MyDslPackage.ASSIGN_NEW_VALUE__GET_REF:
				return getGetRef();
			case MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE:
				return getNewValue();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case MyDslPackage.ASSIGN_NEW_VALUE__GET_REF:
				setGetRef((Ref)newValue);
				return;
			case MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE:
				setNewValue((URDFAttrNumeric)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case MyDslPackage.ASSIGN_NEW_VALUE__GET_REF:
				setGetRef((Ref)null);
				return;
			case MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE:
				setNewValue((URDFAttrNumeric)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case MyDslPackage.ASSIGN_NEW_VALUE__GET_REF:
				return getRef != null;
			case MyDslPackage.ASSIGN_NEW_VALUE__NEW_VALUE:
				return newValue != null;
		}
		return super.eIsSet(featureID);
	}

} //AssignNewValueImpl
