/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.example.mydsl4.myDsl.MyDslFactory;
import org.xtext.example.mydsl4.myDsl.MyDslPackage;
import org.xtext.example.mydsl4.myDsl.Reuse;

/**
 * This is the item provider adapter for a {@link org.xtext.example.mydsl4.myDsl.Reuse} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ReuseItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ReuseItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

		}
		return itemPropertyDescriptors;
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(MyDslPackage.Literals.REUSE__ADD);
			childrenFeatures.add(MyDslPackage.Literals.REUSE__EDIT);
			childrenFeatures.add(MyDslPackage.Literals.REUSE__REF);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns Reuse.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/Reuse"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		return getString("_UI_Reuse_type");
	}
	

	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(Reuse.class)) {
			case MyDslPackage.REUSE__ADD:
			case MyDslPackage.REUSE__EDIT:
			case MyDslPackage.REUSE__REF:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createReUseAble()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createLink()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createURDFAttrSignedNumeric()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createURDFAttrNumeric()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createInertial()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createVisual()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createInertia()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createMass()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createOrigin()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createCollision()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createGeometry()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createBox()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createCylinder()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createMesh()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createSphere()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createMaterial()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createTexture()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createColor()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createJoint()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createAxis()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createLimit()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createCalibration()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createDynamics()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__ADD,
				 MyDslFactory.eINSTANCE.createSafetyController()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__EDIT,
				 MyDslFactory.eINSTANCE.createAssignNewValue()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__REF,
				 MyDslFactory.eINSTANCE.createRef()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__REF,
				 MyDslFactory.eINSTANCE.createReUsableRef()));

		newChildDescriptors.add
			(createChildParameter
				(MyDslPackage.Literals.REUSE__REF,
				 MyDslFactory.eINSTANCE.createDotExpression()));
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return MyDslEditPlugin.INSTANCE;
	}

}
