/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MyDslUiModule extends AbstractMyDslUiModule {
	/*def Class<? extends XtextDocumentProvider> bindDocumentProvider() {
		URDFDocumentProvider;
	}*/
}
