/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add To</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getJoint <em>Joint</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getCollision <em>Collision</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getVisual <em>Visual</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getInertial <em>Inertial</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AddTo#getOrigin <em>Origin</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo()
 * @model
 * @generated
 */
public interface AddTo extends EObject {
	/**
	 * Returns the value of the '<em><b>Link</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Link</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Link</em>' reference.
	 * @see #setLink(Link)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Link()
	 * @model
	 * @generated
	 */
	Link getLink();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.AddTo#getLink <em>Link</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Link</em>' reference.
	 * @see #getLink()
	 * @generated
	 */
	void setLink(Link value);

	/**
	 * Returns the value of the '<em><b>Joint</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Joint</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Joint</em>' reference.
	 * @see #setJoint(Joint)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Joint()
	 * @model
	 * @generated
	 */
	Joint getJoint();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.AddTo#getJoint <em>Joint</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Joint</em>' reference.
	 * @see #getJoint()
	 * @generated
	 */
	void setJoint(Joint value);

	/**
	 * Returns the value of the '<em><b>Collision</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Collision}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Collision</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Collision</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Collision()
	 * @model containment="true"
	 * @generated
	 */
	EList<Collision> getCollision();

	/**
	 * Returns the value of the '<em><b>Visual</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Visual}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Visual</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Visual</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Visual()
	 * @model containment="true"
	 * @generated
	 */
	EList<Visual> getVisual();

	/**
	 * Returns the value of the '<em><b>Inertial</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Inertial}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Inertial</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Inertial</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Inertial()
	 * @model containment="true"
	 * @generated
	 */
	EList<Inertial> getInertial();

	/**
	 * Returns the value of the '<em><b>Origin</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Origin}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Origin</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Origin</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAddTo_Origin()
	 * @model containment="true"
	 * @generated
	 */
	EList<Origin> getOrigin();

} // AddTo
