/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign New Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AssignNewValue#getGetRef <em>Get Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.AssignNewValue#getNewValue <em>New Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAssignNewValue()
 * @model
 * @generated
 */
public interface AssignNewValue extends EObject {
	/**
	 * Returns the value of the '<em><b>Get Ref</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Get Ref</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Get Ref</em>' containment reference.
	 * @see #setGetRef(Ref)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAssignNewValue_GetRef()
	 * @model containment="true" required="true"
	 * @generated
	 */
	Ref getGetRef();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.AssignNewValue#getGetRef <em>Get Ref</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Get Ref</em>' containment reference.
	 * @see #getGetRef()
	 * @generated
	 */
	void setGetRef(Ref value);

	/**
	 * Returns the value of the '<em><b>New Value</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>New Value</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>New Value</em>' containment reference.
	 * @see #setNewValue(URDFAttrNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getAssignNewValue_NewValue()
	 * @model containment="true" required="true"
	 * @generated
	 */
	URDFAttrNumeric getNewValue();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.AssignNewValue#getNewValue <em>New Value</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>New Value</em>' containment reference.
	 * @see #getNewValue()
	 * @generated
	 */
	void setNewValue(URDFAttrNumeric value);

} // AssignNewValue
