/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getColor()
 * @model
 * @generated
 */
public interface Color extends Material {
} // Color
