/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Link#getLink <em>Link</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Link#getReuse <em>Reuse</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Link#getInertial <em>Inertial</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Link#getVisual <em>Visual</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Link#getCollision <em>Collision</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends ReUseAble {
	/**
	 * Returns the value of the '<em><b>Link</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Link</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Link</em>' reference.
	 * @see #setLink(Link)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink_Link()
	 * @model
	 * @generated
	 */
	Link getLink();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Link#getLink <em>Link</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Link</em>' reference.
	 * @see #getLink()
	 * @generated
	 */
	void setLink(Link value);

	/**
	 * Returns the value of the '<em><b>Reuse</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Reuse</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Reuse</em>' containment reference.
	 * @see #setReuse(Reuse)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink_Reuse()
	 * @model containment="true"
	 * @generated
	 */
	Reuse getReuse();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Link#getReuse <em>Reuse</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Reuse</em>' containment reference.
	 * @see #getReuse()
	 * @generated
	 */
	void setReuse(Reuse value);

	/**
	 * Returns the value of the '<em><b>Inertial</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Inertial</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Inertial</em>' containment reference.
	 * @see #setInertial(Inertial)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink_Inertial()
	 * @model containment="true"
	 * @generated
	 */
	Inertial getInertial();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Link#getInertial <em>Inertial</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Inertial</em>' containment reference.
	 * @see #getInertial()
	 * @generated
	 */
	void setInertial(Inertial value);

	/**
	 * Returns the value of the '<em><b>Visual</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Visual}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Visual</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Visual</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink_Visual()
	 * @model containment="true"
	 * @generated
	 */
	EList<Visual> getVisual();

	/**
	 * Returns the value of the '<em><b>Collision</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.mydsl4.myDsl.Collision}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Collision</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Collision</em>' containment reference list.
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getLink_Collision()
	 * @model containment="true"
	 * @generated
	 */
	EList<Collision> getCollision();

} // Link
