/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Material</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getMaterial()
 * @model
 * @generated
 */
public interface Material extends ReUseAble {
} // Material
