/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl4.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "myDsl";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.xtext.org/example/mydsl4/MyDsl";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "myDsl";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	MyDslPackage eINSTANCE = org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl.init();

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.RobotImpl <em>Robot</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.RobotImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getRobot()
	 * @generated
	 */
	int ROBOT = 0;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROBOT__NAME = 0;

	/**
	 * The feature id for the '<em><b>Links</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROBOT__LINKS = 1;

	/**
	 * The feature id for the '<em><b>Joint</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROBOT__JOINT = 2;

	/**
	 * The number of structural features of the '<em>Robot</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ROBOT_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReUseAbleImpl <em>Re Use Able</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.ReUseAbleImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReUseAble()
	 * @generated
	 */
	int RE_USE_ABLE = 1;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RE_USE_ABLE__NAME = 0;

	/**
	 * The number of structural features of the '<em>Re Use Able</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RE_USE_ABLE_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.LinkImpl <em>Link</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.LinkImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getLink()
	 * @generated
	 */
	int LINK = 2;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Link</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__LINK = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Reuse</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__REUSE = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Inertial</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__INERTIAL = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Visual</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__VISUAL = RE_USE_ABLE_FEATURE_COUNT + 3;

	/**
	 * The feature id for the '<em><b>Collision</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK__COLLISION = RE_USE_ABLE_FEATURE_COUNT + 4;

	/**
	 * The number of structural features of the '<em>Link</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int LINK_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 5;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReuseImpl <em>Reuse</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.ReuseImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReuse()
	 * @generated
	 */
	int REUSE = 3;

	/**
	 * The feature id for the '<em><b>Add</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REUSE__ADD = 0;

	/**
	 * The feature id for the '<em><b>Ref</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REUSE__REF = 1;

	/**
	 * The number of structural features of the '<em>Reuse</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REUSE_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.RefImpl <em>Ref</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.RefImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getRef()
	 * @generated
	 */
	int REF = 4;

	/**
	 * The number of structural features of the '<em>Ref</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int REF_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReUsableRefImpl <em>Re Usable Ref</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.ReUsableRefImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReUsableRef()
	 * @generated
	 */
	int RE_USABLE_REF = 5;

	/**
	 * The feature id for the '<em><b>Reuseable</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RE_USABLE_REF__REUSEABLE = REF_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Re Usable Ref</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RE_USABLE_REF_FEATURE_COUNT = REF_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrSignedNumericImpl <em>URDF Attr Signed Numeric</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrSignedNumericImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrSignedNumeric()
	 * @generated
	 */
	int URDF_ATTR_SIGNED_NUMERIC = 6;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_SIGNED_NUMERIC__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_SIGNED_NUMERIC__VALUE = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>URDF Attr Signed Numeric</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_SIGNED_NUMERIC_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrFloatImpl <em>URDF Attr Float</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrFloatImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrFloat()
	 * @generated
	 */
	int URDF_ATTR_FLOAT = 7;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_FLOAT__VALUE = 0;

	/**
	 * The number of structural features of the '<em>URDF Attr Float</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_FLOAT_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrINTImpl <em>URDF Attr INT</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrINTImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrINT()
	 * @generated
	 */
	int URDF_ATTR_INT = 8;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_INT__VALUE = 0;

	/**
	 * The number of structural features of the '<em>URDF Attr INT</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_INT_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrNumericImpl <em>URDF Attr Numeric</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrNumericImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrNumeric()
	 * @generated
	 */
	int URDF_ATTR_NUMERIC = 9;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_NUMERIC__VALUE = 0;

	/**
	 * The number of structural features of the '<em>URDF Attr Numeric</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_NUMERIC_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrSTRINGImpl <em>URDF Attr STRING</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrSTRINGImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrSTRING()
	 * @generated
	 */
	int URDF_ATTR_STRING = 10;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_STRING__VALUE = 0;

	/**
	 * The number of structural features of the '<em>URDF Attr STRING</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int URDF_ATTR_STRING_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.DotExpressionImpl <em>Dot Expression</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.DotExpressionImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getDotExpression()
	 * @generated
	 */
	int DOT_EXPRESSION = 11;

	/**
	 * The feature id for the '<em><b>Ref</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DOT_EXPRESSION__REF = REF_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Tail</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DOT_EXPRESSION__TAIL = REF_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Dot Expression</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DOT_EXPRESSION_FEATURE_COUNT = REF_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.InertialImpl <em>Inertial</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.InertialImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getInertial()
	 * @generated
	 */
	int INERTIAL = 12;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIAL__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Inertia</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIAL__INERTIA = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Mass</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIAL__MASS = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Origin</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIAL__ORIGIN = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Inertial</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIAL_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.VisualImpl <em>Visual</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.VisualImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getVisual()
	 * @generated
	 */
	int VISUAL = 13;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VISUAL__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Origin</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VISUAL__ORIGIN = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Geometry</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VISUAL__GEOMETRY = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Material</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VISUAL__MATERIAL = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Visual</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VISUAL_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 3;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.InertiaImpl <em>Inertia</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.InertiaImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getInertia()
	 * @generated
	 */
	int INERTIA = 14;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Ixx</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IXX = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Ixy</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IXY = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Ixz</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IXZ = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Izz</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IZZ = RE_USE_ABLE_FEATURE_COUNT + 3;

	/**
	 * The feature id for the '<em><b>Iyy</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IYY = RE_USE_ABLE_FEATURE_COUNT + 4;

	/**
	 * The feature id for the '<em><b>Iyz</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA__IYZ = RE_USE_ABLE_FEATURE_COUNT + 5;

	/**
	 * The number of structural features of the '<em>Inertia</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int INERTIA_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 6;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.MassImpl <em>Mass</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.MassImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMass()
	 * @generated
	 */
	int MASS = 15;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MASS__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Mass Kilogram</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MASS__MASS_KILOGRAM = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Mass</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MASS_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 1;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.OriginImpl <em>Origin</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.OriginImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getOrigin()
	 * @generated
	 */
	int ORIGIN = 16;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>X</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__X = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Y</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__Y = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Z</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__Z = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Yaw</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__YAW = RE_USE_ABLE_FEATURE_COUNT + 3;

	/**
	 * The feature id for the '<em><b>Pitch</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__PITCH = RE_USE_ABLE_FEATURE_COUNT + 4;

	/**
	 * The feature id for the '<em><b>Roll</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN__ROLL = RE_USE_ABLE_FEATURE_COUNT + 5;

	/**
	 * The number of structural features of the '<em>Origin</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int ORIGIN_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 6;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.CollisionImpl <em>Collision</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.CollisionImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getCollision()
	 * @generated
	 */
	int COLLISION = 17;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLLISION__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Origin</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLLISION__ORIGIN = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Geometry</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLLISION__GEOMETRY = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Collision</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLLISION_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 2;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.GeometryImpl <em>Geometry</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.GeometryImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getGeometry()
	 * @generated
	 */
	int GEOMETRY = 18;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GEOMETRY__NAME = RE_USE_ABLE__NAME;

	/**
	 * The number of structural features of the '<em>Geometry</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int GEOMETRY_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.BoxImpl <em>Box</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.BoxImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getBox()
	 * @generated
	 */
	int BOX = 19;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int BOX__NAME = GEOMETRY__NAME;

	/**
	 * The feature id for the '<em><b>Width</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int BOX__WIDTH = GEOMETRY_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Length</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int BOX__LENGTH = GEOMETRY_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Height</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int BOX__HEIGHT = GEOMETRY_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Box</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int BOX_FEATURE_COUNT = GEOMETRY_FEATURE_COUNT + 3;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.CylinderImpl <em>Cylinder</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.CylinderImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getCylinder()
	 * @generated
	 */
	int CYLINDER = 20;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CYLINDER__NAME = GEOMETRY__NAME;

	/**
	 * The feature id for the '<em><b>Radius</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CYLINDER__RADIUS = GEOMETRY_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Length</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CYLINDER__LENGTH = GEOMETRY_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Cylinder</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CYLINDER_FEATURE_COUNT = GEOMETRY_FEATURE_COUNT + 2;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.MeshImpl <em>Mesh</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.MeshImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMesh()
	 * @generated
	 */
	int MESH = 21;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MESH__NAME = GEOMETRY__NAME;

	/**
	 * The feature id for the '<em><b>Path To File</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MESH__PATH_TO_FILE = GEOMETRY_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Mesh</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MESH_FEATURE_COUNT = GEOMETRY_FEATURE_COUNT + 1;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.SphereImpl <em>Sphere</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.SphereImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getSphere()
	 * @generated
	 */
	int SPHERE = 22;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPHERE__NAME = GEOMETRY__NAME;

	/**
	 * The feature id for the '<em><b>Radius</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPHERE__RADIUS = GEOMETRY_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Sphere</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int SPHERE_FEATURE_COUNT = GEOMETRY_FEATURE_COUNT + 1;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.MaterialImpl <em>Material</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.MaterialImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMaterial()
	 * @generated
	 */
	int MATERIAL = 23;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MATERIAL__NAME = RE_USE_ABLE__NAME;

	/**
	 * The number of structural features of the '<em>Material</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MATERIAL_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.TextureImpl <em>Texture</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.TextureImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getTexture()
	 * @generated
	 */
	int TEXTURE = 24;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int TEXTURE__NAME = MATERIAL__NAME;

	/**
	 * The feature id for the '<em><b>Path To File</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int TEXTURE__PATH_TO_FILE = MATERIAL_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Texture</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int TEXTURE_FEATURE_COUNT = MATERIAL_FEATURE_COUNT + 1;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.ColorImpl <em>Color</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.ColorImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getColor()
	 * @generated
	 */
	int COLOR = 25;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR__NAME = MATERIAL__NAME;

	/**
	 * The feature id for the '<em><b>Red</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR__RED = MATERIAL_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Green</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR__GREEN = MATERIAL_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Blue</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR__BLUE = MATERIAL_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Alpha</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR__ALPHA = MATERIAL_FEATURE_COUNT + 3;

	/**
	 * The number of structural features of the '<em>Color</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COLOR_FEATURE_COUNT = MATERIAL_FEATURE_COUNT + 4;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.impl.JointImpl <em>Joint</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.impl.JointImpl
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getJoint()
	 * @generated
	 */
	int JOINT = 26;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT__NAME = RE_USE_ABLE__NAME;

	/**
	 * The feature id for the '<em><b>Is Reuse Of</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT__IS_REUSE_OF = RE_USE_ABLE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Child Of</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT__CHILD_OF = RE_USE_ABLE_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Parent Of</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT__PARENT_OF = RE_USE_ABLE_FEATURE_COUNT + 2;

	/**
	 * The feature id for the '<em><b>Type</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT__TYPE = RE_USE_ABLE_FEATURE_COUNT + 3;

	/**
	 * The number of structural features of the '<em>Joint</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int JOINT_FEATURE_COUNT = RE_USE_ABLE_FEATURE_COUNT + 4;


	/**
	 * The meta object id for the '{@link org.xtext.example.mydsl4.myDsl.JointType <em>Joint Type</em>}' enum.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see org.xtext.example.mydsl4.myDsl.JointType
	 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getJointType()
	 * @generated
	 */
	int JOINT_TYPE = 27;


	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Robot <em>Robot</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Robot</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Robot
	 * @generated
	 */
	EClass getRobot();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.Robot#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Robot#getName()
	 * @see #getRobot()
	 * @generated
	 */
	EAttribute getRobot_Name();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Robot#getLinks <em>Links</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Links</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Robot#getLinks()
	 * @see #getRobot()
	 * @generated
	 */
	EReference getRobot_Links();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Robot#getJoint <em>Joint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Joint</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Robot#getJoint()
	 * @see #getRobot()
	 * @generated
	 */
	EReference getRobot_Joint();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.ReUseAble <em>Re Use Able</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Re Use Able</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.ReUseAble
	 * @generated
	 */
	EClass getReUseAble();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.ReUseAble#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.ReUseAble#getName()
	 * @see #getReUseAble()
	 * @generated
	 */
	EAttribute getReUseAble_Name();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Link <em>Link</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Link</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link
	 * @generated
	 */
	EClass getLink();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.Link#getLink <em>Link</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Link</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link#getLink()
	 * @see #getLink()
	 * @generated
	 */
	EReference getLink_Link();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Link#getReuse <em>Reuse</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Reuse</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link#getReuse()
	 * @see #getLink()
	 * @generated
	 */
	EReference getLink_Reuse();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Link#getInertial <em>Inertial</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Inertial</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link#getInertial()
	 * @see #getLink()
	 * @generated
	 */
	EReference getLink_Inertial();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Link#getVisual <em>Visual</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Visual</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link#getVisual()
	 * @see #getLink()
	 * @generated
	 */
	EReference getLink_Visual();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Link#getCollision <em>Collision</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Collision</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Link#getCollision()
	 * @see #getLink()
	 * @generated
	 */
	EReference getLink_Collision();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Reuse <em>Reuse</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Reuse</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Reuse
	 * @generated
	 */
	EClass getReuse();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Reuse#getAdd <em>Add</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Add</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Reuse#getAdd()
	 * @see #getReuse()
	 * @generated
	 */
	EReference getReuse_Add();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Reuse#getRef <em>Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ref</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Reuse#getRef()
	 * @see #getReuse()
	 * @generated
	 */
	EReference getReuse_Ref();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Ref <em>Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Ref</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Ref
	 * @generated
	 */
	EClass getRef();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.ReUsableRef <em>Re Usable Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Re Usable Ref</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.ReUsableRef
	 * @generated
	 */
	EClass getReUsableRef();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.ReUsableRef#getReuseable <em>Reuseable</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Reuseable</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.ReUsableRef#getReuseable()
	 * @see #getReUsableRef()
	 * @generated
	 */
	EReference getReUsableRef_Reuseable();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.URDFAttrSignedNumeric <em>URDF Attr Signed Numeric</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>URDF Attr Signed Numeric</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrSignedNumeric
	 * @generated
	 */
	EClass getURDFAttrSignedNumeric();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.URDFAttrSignedNumeric#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrSignedNumeric#getValue()
	 * @see #getURDFAttrSignedNumeric()
	 * @generated
	 */
	EAttribute getURDFAttrSignedNumeric_Value();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.URDFAttrFloat <em>URDF Attr Float</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>URDF Attr Float</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrFloat
	 * @generated
	 */
	EClass getURDFAttrFloat();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.URDFAttrFloat#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrFloat#getValue()
	 * @see #getURDFAttrFloat()
	 * @generated
	 */
	EAttribute getURDFAttrFloat_Value();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.URDFAttrINT <em>URDF Attr INT</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>URDF Attr INT</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrINT
	 * @generated
	 */
	EClass getURDFAttrINT();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.URDFAttrINT#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrINT#getValue()
	 * @see #getURDFAttrINT()
	 * @generated
	 */
	EAttribute getURDFAttrINT_Value();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.URDFAttrNumeric <em>URDF Attr Numeric</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>URDF Attr Numeric</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrNumeric
	 * @generated
	 */
	EClass getURDFAttrNumeric();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.URDFAttrNumeric#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrNumeric#getValue()
	 * @see #getURDFAttrNumeric()
	 * @generated
	 */
	EAttribute getURDFAttrNumeric_Value();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.URDFAttrSTRING <em>URDF Attr STRING</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>URDF Attr STRING</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrSTRING
	 * @generated
	 */
	EClass getURDFAttrSTRING();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.URDFAttrSTRING#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.URDFAttrSTRING#getValue()
	 * @see #getURDFAttrSTRING()
	 * @generated
	 */
	EAttribute getURDFAttrSTRING_Value();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.DotExpression <em>Dot Expression</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Dot Expression</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.DotExpression
	 * @generated
	 */
	EClass getDotExpression();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.DotExpression#getRef <em>Ref</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ref</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.DotExpression#getRef()
	 * @see #getDotExpression()
	 * @generated
	 */
	EReference getDotExpression_Ref();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.DotExpression#getTail <em>Tail</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Tail</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.DotExpression#getTail()
	 * @see #getDotExpression()
	 * @generated
	 */
	EReference getDotExpression_Tail();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Inertial <em>Inertial</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Inertial</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertial
	 * @generated
	 */
	EClass getInertial();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertial#getInertia <em>Inertia</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Inertia</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertial#getInertia()
	 * @see #getInertial()
	 * @generated
	 */
	EReference getInertial_Inertia();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertial#getMass <em>Mass</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Mass</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertial#getMass()
	 * @see #getInertial()
	 * @generated
	 */
	EReference getInertial_Mass();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertial#getOrigin <em>Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Origin</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertial#getOrigin()
	 * @see #getInertial()
	 * @generated
	 */
	EReference getInertial_Origin();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Visual <em>Visual</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Visual</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Visual
	 * @generated
	 */
	EClass getVisual();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Visual#getOrigin <em>Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Origin</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Visual#getOrigin()
	 * @see #getVisual()
	 * @generated
	 */
	EReference getVisual_Origin();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Visual#getGeometry <em>Geometry</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Geometry</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Visual#getGeometry()
	 * @see #getVisual()
	 * @generated
	 */
	EReference getVisual_Geometry();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Visual#getMaterial <em>Material</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Material</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Visual#getMaterial()
	 * @see #getVisual()
	 * @generated
	 */
	EReference getVisual_Material();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Inertia <em>Inertia</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Inertia</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia
	 * @generated
	 */
	EClass getInertia();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIxx <em>Ixx</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ixx</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIxx()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Ixx();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIxy <em>Ixy</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ixy</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIxy()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Ixy();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIxz <em>Ixz</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ixz</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIxz()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Ixz();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIzz <em>Izz</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Izz</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIzz()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Izz();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIyy <em>Iyy</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Iyy</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIyy()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Iyy();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Inertia#getIyz <em>Iyz</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Iyz</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Inertia#getIyz()
	 * @see #getInertia()
	 * @generated
	 */
	EReference getInertia_Iyz();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Mass <em>Mass</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Mass</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Mass
	 * @generated
	 */
	EClass getMass();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Mass#getMassKilogram <em>Mass Kilogram</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Mass Kilogram</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Mass#getMassKilogram()
	 * @see #getMass()
	 * @generated
	 */
	EReference getMass_MassKilogram();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Origin <em>Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Origin</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin
	 * @generated
	 */
	EClass getOrigin();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getX <em>X</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>X</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getX()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_X();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getY <em>Y</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Y</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getY()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_Y();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getZ <em>Z</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Z</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getZ()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_Z();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getYaw <em>Yaw</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Yaw</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getYaw()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_Yaw();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getPitch <em>Pitch</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Pitch</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getPitch()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_Pitch();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Origin#getRoll <em>Roll</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Roll</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Origin#getRoll()
	 * @see #getOrigin()
	 * @generated
	 */
	EReference getOrigin_Roll();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Collision <em>Collision</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Collision</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Collision
	 * @generated
	 */
	EClass getCollision();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Collision#getOrigin <em>Origin</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Origin</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Collision#getOrigin()
	 * @see #getCollision()
	 * @generated
	 */
	EReference getCollision_Origin();

	/**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl4.myDsl.Collision#getGeometry <em>Geometry</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Geometry</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Collision#getGeometry()
	 * @see #getCollision()
	 * @generated
	 */
	EReference getCollision_Geometry();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Geometry <em>Geometry</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Geometry</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Geometry
	 * @generated
	 */
	EClass getGeometry();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Box <em>Box</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Box</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Box
	 * @generated
	 */
	EClass getBox();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Box#getWidth <em>Width</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Width</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Box#getWidth()
	 * @see #getBox()
	 * @generated
	 */
	EReference getBox_Width();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Box#getLength <em>Length</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Length</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Box#getLength()
	 * @see #getBox()
	 * @generated
	 */
	EReference getBox_Length();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Box#getHeight <em>Height</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Height</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Box#getHeight()
	 * @see #getBox()
	 * @generated
	 */
	EReference getBox_Height();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Cylinder <em>Cylinder</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Cylinder</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Cylinder
	 * @generated
	 */
	EClass getCylinder();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Cylinder#getRadius <em>Radius</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Radius</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Cylinder#getRadius()
	 * @see #getCylinder()
	 * @generated
	 */
	EReference getCylinder_Radius();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Cylinder#getLength <em>Length</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Length</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Cylinder#getLength()
	 * @see #getCylinder()
	 * @generated
	 */
	EReference getCylinder_Length();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Mesh <em>Mesh</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Mesh</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Mesh
	 * @generated
	 */
	EClass getMesh();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Mesh#getPathToFile <em>Path To File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Path To File</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Mesh#getPathToFile()
	 * @see #getMesh()
	 * @generated
	 */
	EReference getMesh_PathToFile();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Sphere <em>Sphere</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Sphere</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Sphere
	 * @generated
	 */
	EClass getSphere();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Sphere#getRadius <em>Radius</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Radius</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Sphere#getRadius()
	 * @see #getSphere()
	 * @generated
	 */
	EReference getSphere_Radius();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Material <em>Material</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Material</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Material
	 * @generated
	 */
	EClass getMaterial();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Texture <em>Texture</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Texture</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Texture
	 * @generated
	 */
	EClass getTexture();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Texture#getPathToFile <em>Path To File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Path To File</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Texture#getPathToFile()
	 * @see #getTexture()
	 * @generated
	 */
	EReference getTexture_PathToFile();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Color <em>Color</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Color</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Color
	 * @generated
	 */
	EClass getColor();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Color#getRed <em>Red</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Red</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Color#getRed()
	 * @see #getColor()
	 * @generated
	 */
	EReference getColor_Red();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Color#getGreen <em>Green</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Green</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Color#getGreen()
	 * @see #getColor()
	 * @generated
	 */
	EReference getColor_Green();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Color#getBlue <em>Blue</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Blue</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Color#getBlue()
	 * @see #getColor()
	 * @generated
	 */
	EReference getColor_Blue();

	/**
	 * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl4.myDsl.Color#getAlpha <em>Alpha</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Alpha</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Color#getAlpha()
	 * @see #getColor()
	 * @generated
	 */
	EReference getColor_Alpha();

	/**
	 * Returns the meta object for class '{@link org.xtext.example.mydsl4.myDsl.Joint <em>Joint</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Joint</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Joint
	 * @generated
	 */
	EClass getJoint();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.Joint#getIsReuseOf <em>Is Reuse Of</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Is Reuse Of</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Joint#getIsReuseOf()
	 * @see #getJoint()
	 * @generated
	 */
	EReference getJoint_IsReuseOf();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.Joint#getChildOf <em>Child Of</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Child Of</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Joint#getChildOf()
	 * @see #getJoint()
	 * @generated
	 */
	EReference getJoint_ChildOf();

	/**
	 * Returns the meta object for the reference '{@link org.xtext.example.mydsl4.myDsl.Joint#getParentOf <em>Parent Of</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Parent Of</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Joint#getParentOf()
	 * @see #getJoint()
	 * @generated
	 */
	EReference getJoint_ParentOf();

	/**
	 * Returns the meta object for the attribute '{@link org.xtext.example.mydsl4.myDsl.Joint#getType <em>Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Type</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.Joint#getType()
	 * @see #getJoint()
	 * @generated
	 */
	EAttribute getJoint_Type();

	/**
	 * Returns the meta object for enum '{@link org.xtext.example.mydsl4.myDsl.JointType <em>Joint Type</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Joint Type</em>'.
	 * @see org.xtext.example.mydsl4.myDsl.JointType
	 * @generated
	 */
	EEnum getJointType();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	MyDslFactory getMyDslFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.RobotImpl <em>Robot</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.RobotImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getRobot()
		 * @generated
		 */
		EClass ROBOT = eINSTANCE.getRobot();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

		/**
		 * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ROBOT__LINKS = eINSTANCE.getRobot_Links();

		/**
		 * The meta object literal for the '<em><b>Joint</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ROBOT__JOINT = eINSTANCE.getRobot_Joint();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReUseAbleImpl <em>Re Use Able</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.ReUseAbleImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReUseAble()
		 * @generated
		 */
		EClass RE_USE_ABLE = eINSTANCE.getReUseAble();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute RE_USE_ABLE__NAME = eINSTANCE.getReUseAble_Name();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.LinkImpl <em>Link</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.LinkImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getLink()
		 * @generated
		 */
		EClass LINK = eINSTANCE.getLink();

		/**
		 * The meta object literal for the '<em><b>Link</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference LINK__LINK = eINSTANCE.getLink_Link();

		/**
		 * The meta object literal for the '<em><b>Reuse</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference LINK__REUSE = eINSTANCE.getLink_Reuse();

		/**
		 * The meta object literal for the '<em><b>Inertial</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference LINK__INERTIAL = eINSTANCE.getLink_Inertial();

		/**
		 * The meta object literal for the '<em><b>Visual</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference LINK__VISUAL = eINSTANCE.getLink_Visual();

		/**
		 * The meta object literal for the '<em><b>Collision</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference LINK__COLLISION = eINSTANCE.getLink_Collision();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReuseImpl <em>Reuse</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.ReuseImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReuse()
		 * @generated
		 */
		EClass REUSE = eINSTANCE.getReuse();

		/**
		 * The meta object literal for the '<em><b>Add</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference REUSE__ADD = eINSTANCE.getReuse_Add();

		/**
		 * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference REUSE__REF = eINSTANCE.getReuse_Ref();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.RefImpl <em>Ref</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.RefImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getRef()
		 * @generated
		 */
		EClass REF = eINSTANCE.getRef();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.ReUsableRefImpl <em>Re Usable Ref</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.ReUsableRefImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getReUsableRef()
		 * @generated
		 */
		EClass RE_USABLE_REF = eINSTANCE.getReUsableRef();

		/**
		 * The meta object literal for the '<em><b>Reuseable</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference RE_USABLE_REF__REUSEABLE = eINSTANCE.getReUsableRef_Reuseable();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrSignedNumericImpl <em>URDF Attr Signed Numeric</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrSignedNumericImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrSignedNumeric()
		 * @generated
		 */
		EClass URDF_ATTR_SIGNED_NUMERIC = eINSTANCE.getURDFAttrSignedNumeric();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute URDF_ATTR_SIGNED_NUMERIC__VALUE = eINSTANCE.getURDFAttrSignedNumeric_Value();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrFloatImpl <em>URDF Attr Float</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrFloatImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrFloat()
		 * @generated
		 */
		EClass URDF_ATTR_FLOAT = eINSTANCE.getURDFAttrFloat();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute URDF_ATTR_FLOAT__VALUE = eINSTANCE.getURDFAttrFloat_Value();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrINTImpl <em>URDF Attr INT</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrINTImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrINT()
		 * @generated
		 */
		EClass URDF_ATTR_INT = eINSTANCE.getURDFAttrINT();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute URDF_ATTR_INT__VALUE = eINSTANCE.getURDFAttrINT_Value();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrNumericImpl <em>URDF Attr Numeric</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrNumericImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrNumeric()
		 * @generated
		 */
		EClass URDF_ATTR_NUMERIC = eINSTANCE.getURDFAttrNumeric();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute URDF_ATTR_NUMERIC__VALUE = eINSTANCE.getURDFAttrNumeric_Value();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.URDFAttrSTRINGImpl <em>URDF Attr STRING</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.URDFAttrSTRINGImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getURDFAttrSTRING()
		 * @generated
		 */
		EClass URDF_ATTR_STRING = eINSTANCE.getURDFAttrSTRING();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute URDF_ATTR_STRING__VALUE = eINSTANCE.getURDFAttrSTRING_Value();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.DotExpressionImpl <em>Dot Expression</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.DotExpressionImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getDotExpression()
		 * @generated
		 */
		EClass DOT_EXPRESSION = eINSTANCE.getDotExpression();

		/**
		 * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DOT_EXPRESSION__REF = eINSTANCE.getDotExpression_Ref();

		/**
		 * The meta object literal for the '<em><b>Tail</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DOT_EXPRESSION__TAIL = eINSTANCE.getDotExpression_Tail();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.InertialImpl <em>Inertial</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.InertialImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getInertial()
		 * @generated
		 */
		EClass INERTIAL = eINSTANCE.getInertial();

		/**
		 * The meta object literal for the '<em><b>Inertia</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIAL__INERTIA = eINSTANCE.getInertial_Inertia();

		/**
		 * The meta object literal for the '<em><b>Mass</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIAL__MASS = eINSTANCE.getInertial_Mass();

		/**
		 * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIAL__ORIGIN = eINSTANCE.getInertial_Origin();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.VisualImpl <em>Visual</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.VisualImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getVisual()
		 * @generated
		 */
		EClass VISUAL = eINSTANCE.getVisual();

		/**
		 * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VISUAL__ORIGIN = eINSTANCE.getVisual_Origin();

		/**
		 * The meta object literal for the '<em><b>Geometry</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VISUAL__GEOMETRY = eINSTANCE.getVisual_Geometry();

		/**
		 * The meta object literal for the '<em><b>Material</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VISUAL__MATERIAL = eINSTANCE.getVisual_Material();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.InertiaImpl <em>Inertia</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.InertiaImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getInertia()
		 * @generated
		 */
		EClass INERTIA = eINSTANCE.getInertia();

		/**
		 * The meta object literal for the '<em><b>Ixx</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IXX = eINSTANCE.getInertia_Ixx();

		/**
		 * The meta object literal for the '<em><b>Ixy</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IXY = eINSTANCE.getInertia_Ixy();

		/**
		 * The meta object literal for the '<em><b>Ixz</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IXZ = eINSTANCE.getInertia_Ixz();

		/**
		 * The meta object literal for the '<em><b>Izz</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IZZ = eINSTANCE.getInertia_Izz();

		/**
		 * The meta object literal for the '<em><b>Iyy</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IYY = eINSTANCE.getInertia_Iyy();

		/**
		 * The meta object literal for the '<em><b>Iyz</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference INERTIA__IYZ = eINSTANCE.getInertia_Iyz();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.MassImpl <em>Mass</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.MassImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMass()
		 * @generated
		 */
		EClass MASS = eINSTANCE.getMass();

		/**
		 * The meta object literal for the '<em><b>Mass Kilogram</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MASS__MASS_KILOGRAM = eINSTANCE.getMass_MassKilogram();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.OriginImpl <em>Origin</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.OriginImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getOrigin()
		 * @generated
		 */
		EClass ORIGIN = eINSTANCE.getOrigin();

		/**
		 * The meta object literal for the '<em><b>X</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__X = eINSTANCE.getOrigin_X();

		/**
		 * The meta object literal for the '<em><b>Y</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__Y = eINSTANCE.getOrigin_Y();

		/**
		 * The meta object literal for the '<em><b>Z</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__Z = eINSTANCE.getOrigin_Z();

		/**
		 * The meta object literal for the '<em><b>Yaw</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__YAW = eINSTANCE.getOrigin_Yaw();

		/**
		 * The meta object literal for the '<em><b>Pitch</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__PITCH = eINSTANCE.getOrigin_Pitch();

		/**
		 * The meta object literal for the '<em><b>Roll</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference ORIGIN__ROLL = eINSTANCE.getOrigin_Roll();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.CollisionImpl <em>Collision</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.CollisionImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getCollision()
		 * @generated
		 */
		EClass COLLISION = eINSTANCE.getCollision();

		/**
		 * The meta object literal for the '<em><b>Origin</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLLISION__ORIGIN = eINSTANCE.getCollision_Origin();

		/**
		 * The meta object literal for the '<em><b>Geometry</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLLISION__GEOMETRY = eINSTANCE.getCollision_Geometry();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.GeometryImpl <em>Geometry</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.GeometryImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getGeometry()
		 * @generated
		 */
		EClass GEOMETRY = eINSTANCE.getGeometry();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.BoxImpl <em>Box</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.BoxImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getBox()
		 * @generated
		 */
		EClass BOX = eINSTANCE.getBox();

		/**
		 * The meta object literal for the '<em><b>Width</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference BOX__WIDTH = eINSTANCE.getBox_Width();

		/**
		 * The meta object literal for the '<em><b>Length</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference BOX__LENGTH = eINSTANCE.getBox_Length();

		/**
		 * The meta object literal for the '<em><b>Height</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference BOX__HEIGHT = eINSTANCE.getBox_Height();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.CylinderImpl <em>Cylinder</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.CylinderImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getCylinder()
		 * @generated
		 */
		EClass CYLINDER = eINSTANCE.getCylinder();

		/**
		 * The meta object literal for the '<em><b>Radius</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CYLINDER__RADIUS = eINSTANCE.getCylinder_Radius();

		/**
		 * The meta object literal for the '<em><b>Length</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CYLINDER__LENGTH = eINSTANCE.getCylinder_Length();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.MeshImpl <em>Mesh</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.MeshImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMesh()
		 * @generated
		 */
		EClass MESH = eINSTANCE.getMesh();

		/**
		 * The meta object literal for the '<em><b>Path To File</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MESH__PATH_TO_FILE = eINSTANCE.getMesh_PathToFile();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.SphereImpl <em>Sphere</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.SphereImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getSphere()
		 * @generated
		 */
		EClass SPHERE = eINSTANCE.getSphere();

		/**
		 * The meta object literal for the '<em><b>Radius</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference SPHERE__RADIUS = eINSTANCE.getSphere_Radius();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.MaterialImpl <em>Material</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.MaterialImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getMaterial()
		 * @generated
		 */
		EClass MATERIAL = eINSTANCE.getMaterial();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.TextureImpl <em>Texture</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.TextureImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getTexture()
		 * @generated
		 */
		EClass TEXTURE = eINSTANCE.getTexture();

		/**
		 * The meta object literal for the '<em><b>Path To File</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference TEXTURE__PATH_TO_FILE = eINSTANCE.getTexture_PathToFile();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.ColorImpl <em>Color</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.ColorImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getColor()
		 * @generated
		 */
		EClass COLOR = eINSTANCE.getColor();

		/**
		 * The meta object literal for the '<em><b>Red</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLOR__RED = eINSTANCE.getColor_Red();

		/**
		 * The meta object literal for the '<em><b>Green</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLOR__GREEN = eINSTANCE.getColor_Green();

		/**
		 * The meta object literal for the '<em><b>Blue</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLOR__BLUE = eINSTANCE.getColor_Blue();

		/**
		 * The meta object literal for the '<em><b>Alpha</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference COLOR__ALPHA = eINSTANCE.getColor_Alpha();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.impl.JointImpl <em>Joint</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.impl.JointImpl
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getJoint()
		 * @generated
		 */
		EClass JOINT = eINSTANCE.getJoint();

		/**
		 * The meta object literal for the '<em><b>Is Reuse Of</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference JOINT__IS_REUSE_OF = eINSTANCE.getJoint_IsReuseOf();

		/**
		 * The meta object literal for the '<em><b>Child Of</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference JOINT__CHILD_OF = eINSTANCE.getJoint_ChildOf();

		/**
		 * The meta object literal for the '<em><b>Parent Of</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference JOINT__PARENT_OF = eINSTANCE.getJoint_ParentOf();

		/**
		 * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute JOINT__TYPE = eINSTANCE.getJoint_Type();

		/**
		 * The meta object literal for the '{@link org.xtext.example.mydsl4.myDsl.JointType <em>Joint Type</em>}' enum.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see org.xtext.example.mydsl4.myDsl.JointType
		 * @see org.xtext.example.mydsl4.myDsl.impl.MyDslPackageImpl#getJointType()
		 * @generated
		 */
		EEnum JOINT_TYPE = eINSTANCE.getJointType();

	}

} //MyDslPackage
