/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Origin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getZ <em>Z</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getYaw <em>Yaw</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getPitch <em>Pitch</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Origin#getRoll <em>Roll</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin()
 * @model
 * @generated
 */
public interface Origin extends ReUseAble {
	/**
	 * Returns the value of the '<em><b>X</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>X</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>X</em>' containment reference.
	 * @see #setX(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_X()
	 * @model containment="true" required="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getX();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getX <em>X</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>X</em>' containment reference.
	 * @see #getX()
	 * @generated
	 */
	void setX(URDFAttrSignedNumeric value);

	/**
	 * Returns the value of the '<em><b>Y</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Y</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Y</em>' containment reference.
	 * @see #setY(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_Y()
	 * @model containment="true" required="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getY();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getY <em>Y</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Y</em>' containment reference.
	 * @see #getY()
	 * @generated
	 */
	void setY(URDFAttrSignedNumeric value);

	/**
	 * Returns the value of the '<em><b>Z</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Z</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Z</em>' containment reference.
	 * @see #setZ(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_Z()
	 * @model containment="true" required="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getZ();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getZ <em>Z</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Z</em>' containment reference.
	 * @see #getZ()
	 * @generated
	 */
	void setZ(URDFAttrSignedNumeric value);

	/**
	 * Returns the value of the '<em><b>Yaw</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Yaw</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Yaw</em>' containment reference.
	 * @see #setYaw(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_Yaw()
	 * @model containment="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getYaw();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getYaw <em>Yaw</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Yaw</em>' containment reference.
	 * @see #getYaw()
	 * @generated
	 */
	void setYaw(URDFAttrSignedNumeric value);

	/**
	 * Returns the value of the '<em><b>Pitch</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Pitch</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Pitch</em>' containment reference.
	 * @see #setPitch(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_Pitch()
	 * @model containment="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getPitch();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getPitch <em>Pitch</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Pitch</em>' containment reference.
	 * @see #getPitch()
	 * @generated
	 */
	void setPitch(URDFAttrSignedNumeric value);

	/**
	 * Returns the value of the '<em><b>Roll</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Roll</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Roll</em>' containment reference.
	 * @see #setRoll(URDFAttrSignedNumeric)
	 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getOrigin_Roll()
	 * @model containment="true"
	 * @generated
	 */
	URDFAttrSignedNumeric getRoll();

	/**
	 * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Origin#getRoll <em>Roll</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Roll</em>' containment reference.
	 * @see #getRoll()
	 * @generated
	 */
	void setRoll(URDFAttrSignedNumeric value);

} // Origin
