/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl4.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl4.myDsl.Axis;
import org.xtext.example.mydsl4.myDsl.Box;
import org.xtext.example.mydsl4.myDsl.Calibration;
import org.xtext.example.mydsl4.myDsl.Collision;
import org.xtext.example.mydsl4.myDsl.Color;
import org.xtext.example.mydsl4.myDsl.Cylinder;
import org.xtext.example.mydsl4.myDsl.DotExpression;
import org.xtext.example.mydsl4.myDsl.Dynamics;
import org.xtext.example.mydsl4.myDsl.Inertia;
import org.xtext.example.mydsl4.myDsl.Inertial;
import org.xtext.example.mydsl4.myDsl.Joint;
import org.xtext.example.mydsl4.myDsl.JointRef;
import org.xtext.example.mydsl4.myDsl.Limit;
import org.xtext.example.mydsl4.myDsl.Link;
import org.xtext.example.mydsl4.myDsl.Mass;
import org.xtext.example.mydsl4.myDsl.Mesh;
import org.xtext.example.mydsl4.myDsl.MyDslPackage;
import org.xtext.example.mydsl4.myDsl.Origin;
import org.xtext.example.mydsl4.myDsl.ReUsableRef;
import org.xtext.example.mydsl4.myDsl.Reuse;
import org.xtext.example.mydsl4.myDsl.Robot;
import org.xtext.example.mydsl4.myDsl.SafetyController;
import org.xtext.example.mydsl4.myDsl.Sphere;
import org.xtext.example.mydsl4.myDsl.Texture;
import org.xtext.example.mydsl4.myDsl.Topology;
import org.xtext.example.mydsl4.myDsl.URDFAttrFloat;
import org.xtext.example.mydsl4.myDsl.URDFAttrINT;
import org.xtext.example.mydsl4.myDsl.URDFAttrNumeric;
import org.xtext.example.mydsl4.myDsl.URDFAttrSTRING;
import org.xtext.example.mydsl4.myDsl.URDFAttrSignedNumeric;
import org.xtext.example.mydsl4.myDsl.Visual;
import org.xtext.example.mydsl4.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.AXIS:
				sequence_Axis(context, (Axis) semanticObject); 
				return; 
			case MyDslPackage.BOX:
				sequence_Box(context, (Box) semanticObject); 
				return; 
			case MyDslPackage.CALIBRATION:
				sequence_Calibration(context, (Calibration) semanticObject); 
				return; 
			case MyDslPackage.COLLISION:
				sequence_Collision(context, (Collision) semanticObject); 
				return; 
			case MyDslPackage.COLOR:
				sequence_Color(context, (Color) semanticObject); 
				return; 
			case MyDslPackage.CYLINDER:
				sequence_Cylinder(context, (Cylinder) semanticObject); 
				return; 
			case MyDslPackage.DOT_EXPRESSION:
				sequence_DotExpression(context, (DotExpression) semanticObject); 
				return; 
			case MyDslPackage.DYNAMICS:
				sequence_Dynamics(context, (Dynamics) semanticObject); 
				return; 
			case MyDslPackage.INERTIA:
				sequence_Inertia(context, (Inertia) semanticObject); 
				return; 
			case MyDslPackage.INERTIAL:
				sequence_Inertial(context, (Inertial) semanticObject); 
				return; 
			case MyDslPackage.JOINT:
				sequence_Joint(context, (Joint) semanticObject); 
				return; 
			case MyDslPackage.JOINT_REF:
				sequence_JointRef(context, (JointRef) semanticObject); 
				return; 
			case MyDslPackage.LIMIT:
				sequence_Limit(context, (Limit) semanticObject); 
				return; 
			case MyDslPackage.LINK:
				sequence_Link(context, (Link) semanticObject); 
				return; 
			case MyDslPackage.MASS:
				sequence_Mass(context, (Mass) semanticObject); 
				return; 
			case MyDslPackage.MESH:
				sequence_Mesh(context, (Mesh) semanticObject); 
				return; 
			case MyDslPackage.ORIGIN:
				sequence_Origin(context, (Origin) semanticObject); 
				return; 
			case MyDslPackage.RE_USABLE_REF:
				sequence_ReUsableRef(context, (ReUsableRef) semanticObject); 
				return; 
			case MyDslPackage.REUSE:
				sequence_Reuse(context, (Reuse) semanticObject); 
				return; 
			case MyDslPackage.ROBOT:
				sequence_Robot(context, (Robot) semanticObject); 
				return; 
			case MyDslPackage.SAFETY_CONTROLLER:
				sequence_SafetyController(context, (SafetyController) semanticObject); 
				return; 
			case MyDslPackage.SPHERE:
				sequence_Sphere(context, (Sphere) semanticObject); 
				return; 
			case MyDslPackage.TEXTURE:
				sequence_Texture(context, (Texture) semanticObject); 
				return; 
			case MyDslPackage.TOPOLOGY:
				sequence_Topology(context, (Topology) semanticObject); 
				return; 
			case MyDslPackage.URDF_ATTR_FLOAT:
				sequence_URDFAttrFloat(context, (URDFAttrFloat) semanticObject); 
				return; 
			case MyDslPackage.URDF_ATTR_INT:
				sequence_URDFAttrINT(context, (URDFAttrINT) semanticObject); 
				return; 
			case MyDslPackage.URDF_ATTR_NUMERIC:
				sequence_URDFAttrNumeric(context, (URDFAttrNumeric) semanticObject); 
				return; 
			case MyDslPackage.URDF_ATTR_STRING:
				sequence_URDFAttrSTRING(context, (URDFAttrSTRING) semanticObject); 
				return; 
			case MyDslPackage.URDF_ATTR_SIGNED_NUMERIC:
				sequence_URDFAttrSignedNumeric(context, (URDFAttrSignedNumeric) semanticObject); 
				return; 
			case MyDslPackage.VISUAL:
				sequence_Visual(context, (Visual) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Axis returns Axis
	 *
	 * Constraint:
	 *     (name=ID? x=URDFAttrINT y=URDFAttrINT z=URDFAttrINT)
	 */
	protected void sequence_Axis(ISerializationContext context, Axis semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Box
	 *     Box returns Box
	 *
	 * Constraint:
	 *     (name=ID? height=URDFAttrNumeric length=URDFAttrNumeric width=URDFAttrNumeric)
	 */
	protected void sequence_Box(ISerializationContext context, Box semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Calibration returns Calibration
	 *
	 * Constraint:
	 *     (name=ID? rising=URDFAttrSignedNumeric? falling=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Calibration(ISerializationContext context, Calibration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ReUseAble returns Collision
	 *     Collision returns Collision
	 *
	 * Constraint:
	 *     (name=ID? geometry+=Geometry+ origin=Origin?)
	 */
	protected void sequence_Collision(ISerializationContext context, Collision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Material returns Color
	 *     Color returns Color
	 *
	 * Constraint:
	 *     (name=ID? red=URDFAttrFloat green=URDFAttrFloat blue=URDFAttrFloat alpha=URDFAttrFloat)
	 */
	protected void sequence_Color(ISerializationContext context, Color semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Cylinder
	 *     Cylinder returns Cylinder
	 *
	 * Constraint:
	 *     (name=ID? radius=URDFAttrNumeric length=URDFAttrNumeric)
	 */
	protected void sequence_Cylinder(ISerializationContext context, Cylinder semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DotExpression returns DotExpression
	 *     DotExpression.DotExpression_1_0 returns DotExpression
	 *
	 * Constraint:
	 *     (ref=DotExpression_DotExpression_1_0 tail=[ReUseAble|ID])
	 */
	protected void sequence_DotExpression(ISerializationContext context, DotExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.DOT_EXPRESSION__REF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.DOT_EXPRESSION__REF));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.DOT_EXPRESSION__TAIL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.DOT_EXPRESSION__TAIL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDotExpressionAccess().getDotExpressionRefAction_1_0(), semanticObject.getRef());
		feeder.accept(grammarAccess.getDotExpressionAccess().getTailReUseAbleIDTerminalRuleCall_1_2_0_1(), semanticObject.getTail());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Dynamics returns Dynamics
	 *
	 * Constraint:
	 *     (name=ID? friction=URDFAttrSignedNumeric? damping=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Dynamics(ISerializationContext context, Dynamics semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Inertia returns Inertia
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         ixx=URDFAttrSignedNumeric 
	 *         ixy=URDFAttrSignedNumeric 
	 *         ixz=URDFAttrSignedNumeric 
	 *         iyy=URDFAttrSignedNumeric 
	 *         iyz=URDFAttrSignedNumeric 
	 *         izz=URDFAttrSignedNumeric
	 *     )
	 */
	protected void sequence_Inertia(ISerializationContext context, Inertia semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ReUseAble returns Inertial
	 *     Inertial returns Inertial
	 *
	 * Constraint:
	 *     (name=ID? inertia=Inertia mass=Mass origin=Origin?)
	 */
	protected void sequence_Inertial(ISerializationContext context, Inertial semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JointRef returns JointRef
	 *
	 * Constraint:
	 *     (fix='->' | rev='r->' | pris='p->' | cont='c->')
	 */
	protected void sequence_JointRef(ISerializationContext context, JointRef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Joint returns Joint
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         (
	 *             (
	 *                 childOf=[Link|ID] 
	 *                 parentOf=[Link|ID] 
	 *                 type=JointType 
	 *                 (
	 *                     origin=Origin | 
	 *                     axis=Axis | 
	 *                     limit=Limit | 
	 *                     calibration=Calibration | 
	 *                     dynamics=Dynamics | 
	 *                     safetycontroller=SafetyController
	 *                 )*
	 *             ) | 
	 *             (isReuseOf=[Joint|ID] childOf=[Link|ID] parentOf=[Link|ID] reuse=Reuse)
	 *         )?
	 *     )
	 */
	protected void sequence_Joint(ISerializationContext context, Joint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Limit returns Limit
	 *
	 * Constraint:
	 *     (name=ID? effort=URDFAttrSignedNumeric velocity=URDFAttrSignedNumeric lower=URDFAttrSignedNumeric? upper=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Limit(ISerializationContext context, Limit semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ReUseAble returns Link
	 *     Link returns Link
	 *
	 * Constraint:
	 *     (name=ID ((inertial=Inertial | visual+=Visual | collision+=Collision)+ | (link=[Link|ID] reuse=Reuse))?)
	 */
	protected void sequence_Link(ISerializationContext context, Link semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Mass returns Mass
	 *
	 * Constraint:
	 *     (name=ID? massKilogram=URDFAttrSignedNumeric)
	 */
	protected void sequence_Mass(ISerializationContext context, Mass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Mesh
	 *     Mesh returns Mesh
	 *
	 * Constraint:
	 *     (name=ID? pathToFile=URDFAttrSTRING)
	 */
	protected void sequence_Mesh(ISerializationContext context, Mesh semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Origin returns Origin
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         x=URDFAttrSignedNumeric 
	 *         y=URDFAttrSignedNumeric 
	 *         z=URDFAttrSignedNumeric 
	 *         roll=URDFAttrSignedNumeric? 
	 *         pitch=URDFAttrSignedNumeric? 
	 *         yaw=URDFAttrSignedNumeric?
	 *     )
	 */
	protected void sequence_Origin(ISerializationContext context, Origin semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DotExpression returns ReUsableRef
	 *     DotExpression.DotExpression_1_0 returns ReUsableRef
	 *     ReUsableRef returns ReUsableRef
	 *
	 * Constraint:
	 *     reuseable=[ReUseAble|ID]
	 */
	protected void sequence_ReUsableRef(ISerializationContext context, ReUsableRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.RE_USABLE_REF__REUSEABLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.RE_USABLE_REF__REUSEABLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReUsableRefAccess().getReuseableReUseAbleIDTerminalRuleCall_1_0_1(), semanticObject.getReuseable());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Reuse returns Reuse
	 *
	 * Constraint:
	 *     (ref=DotExpression | add=ReUseAble)?
	 */
	protected void sequence_Reuse(ISerializationContext context, Reuse semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Robot returns Robot
	 *
	 * Constraint:
	 *     (name=ID (topologies+=Topology | links+=Link | joint+=Joint)*)
	 */
	protected void sequence_Robot(ISerializationContext context, Robot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SafetyController returns SafetyController
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         k_velocity=URDFAttrSignedNumeric 
	 *         k_position=URDFAttrSignedNumeric? 
	 *         softLowerLimit=URDFAttrSignedNumeric? 
	 *         softUpperLimit=URDFAttrSignedNumeric?
	 *     )
	 */
	protected void sequence_SafetyController(ISerializationContext context, SafetyController semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Sphere
	 *     Sphere returns Sphere
	 *
	 * Constraint:
	 *     (name=ID? radius=URDFAttrNumeric)
	 */
	protected void sequence_Sphere(ISerializationContext context, Sphere semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Material returns Texture
	 *     Texture returns Texture
	 *
	 * Constraint:
	 *     (name=ID? pathToFile=URDFAttrSTRING)
	 */
	protected void sequence_Texture(ISerializationContext context, Texture semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Topology returns Topology
	 *
	 * Constraint:
	 *     (parent=[Link|ID] (joint=JointRef child=Topology)?)
	 */
	protected void sequence_Topology(ISerializationContext context, Topology semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrFloat returns URDFAttrFloat
	 *
	 * Constraint:
	 *     value=FLOAT
	 */
	protected void sequence_URDFAttrFloat(ISerializationContext context, URDFAttrFloat semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.URDF_ATTR_FLOAT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.URDF_ATTR_FLOAT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrFloatAccess().getValueFLOATParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrINT returns URDFAttrINT
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_URDFAttrINT(ISerializationContext context, URDFAttrINT semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.URDF_ATTR_INT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.URDF_ATTR_INT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrINTAccess().getValueINTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrNumeric returns URDFAttrNumeric
	 *
	 * Constraint:
	 *     value=NUMERIC
	 */
	protected void sequence_URDFAttrNumeric(ISerializationContext context, URDFAttrNumeric semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.URDF_ATTR_NUMERIC__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.URDF_ATTR_NUMERIC__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrNumericAccess().getValueNUMERICParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrSTRING returns URDFAttrSTRING
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_URDFAttrSTRING(ISerializationContext context, URDFAttrSTRING semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.URDF_ATTR_STRING__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.URDF_ATTR_STRING__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrSTRINGAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrSignedNumeric returns URDFAttrSignedNumeric
	 *
	 * Constraint:
	 *     (name=ID? value=SIGNED_NUMERIC)
	 */
	protected void sequence_URDFAttrSignedNumeric(ISerializationContext context, URDFAttrSignedNumeric semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ReUseAble returns Visual
	 *     Visual returns Visual
	 *
	 * Constraint:
	 *     (name=ID? geometry+=Geometry+ origin=Origin? material=Material?)
	 */
	protected void sequence_Visual(ISerializationContext context, Visual semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
